create table if not exists public.profile (
  id bigint generated by default as identity primary key,
  "fullName" text not null,
  email text unique not null,
  password text not null,
  mobile text,
  country text,
  "employeeId" text,
  department text,
  position text,
  created_at timestamptz not null default now()
);

create table if not exists public.colleges_agreements (
  id bigint generated by default as identity primary key,
  "providerId" text unique not null,
  "tradingName" text not null,
  "instituteName" text not null,
  "cricosCode" text,
  "websiteLink" text,
  "hasAgreement" text,
  "agreementName" text,
  status text,
  remark text,
  "startDate" date,
  "expireDate" date,
  "renewalDate" date,
  "filePath" text,
  created_at timestamptz not null default now()
);

create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  "courseId" text unique not null,
  "tradingName" text not null,
  "courseName" text not null,
  "cricosCode" text,
  "totalFee" text,
  duration text,
  state text,
  created_at timestamptz not null default now()
);

create table if not exists public.flyers (
  id bigint generated by default as identity primary key,
  "providerId" bigint not null,
  "filePath" text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.enrolments (
  id bigint generated by default as identity primary key,
  "collegeId" bigint,
  "enrolmentUrl" text,
  username text,
  password text,
  email text,
  "formsData" jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_flyers_provider_id on public.flyers ("providerId");
create index if not exists idx_enrolments_college_id on public.enrolments ("collegeId");

alter table public.flyers disable row level security;
alter table public.enrolments disable row level security;

grant select, insert, update, delete on public.flyers to anon, authenticated, service_role;
grant select, insert, update, delete on public.enrolments to anon, authenticated, service_role;

notify pgrst, 'reload schema';

insert into public.profile
("fullName", email, password, mobile, country, "employeeId", department, position)
values
  ('Admin User', 'admin@nals.local', 'admin123', '0411000001', 'Australia', 'EMP-001', 'IT', 'Administrator'),
  ('Admissions Manager', 'admissions@nals.local', 'admissions123', '0411000002', 'Australia', 'EMP-002', 'Operations', 'Manager')
on conflict (email) do update
set
  "fullName" = excluded."fullName",
  password = excluded.password,
  mobile = excluded.mobile,
  country = excluded.country,
  "employeeId" = excluded."employeeId",
  department = excluded.department,
  position = excluded.position;

insert into public.colleges_agreements
("providerId", "tradingName", "instituteName", "cricosCode", "websiteLink", "hasAgreement")
values
  ('PVD-1001', 'NALS College Sydney', 'NALS Institute of Business', '010203A', 'https://example.edu.au', 'Yes'),
  ('PVD-1002', 'NALS College Melbourne', 'NALS Institute of Technology', '020304B', 'https://example-tech.edu.au', 'No')
on conflict ("providerId") do update
set
  "tradingName" = excluded."tradingName",
  "instituteName" = excluded."instituteName",
  "cricosCode" = excluded."cricosCode",
  "websiteLink" = excluded."websiteLink",
  "hasAgreement" = excluded."hasAgreement";

insert into public.courses
("courseId", "tradingName", "courseName", "cricosCode", "totalFee", duration, state)
values
  ('CRS-1001', 'NALS College Sydney', 'Diploma of Information Technology', '111111A', '12000', '52 weeks', 'NSW'),
  ('CRS-1002', 'NALS College Melbourne', 'Advanced Diploma of Leadership', '222222B', '9800', '48 weeks', 'VIC')
on conflict ("courseId") do update
set
  "tradingName" = excluded."tradingName",
  "courseName" = excluded."courseName",
  "cricosCode" = excluded."cricosCode",
  "totalFee" = excluded."totalFee",
  duration = excluded.duration,
  state = excluded.state;

insert into public.flyers ("providerId", "filePath")
select id, 'sample-flyer.pdf'
from public.colleges_agreements
where
  "providerId" = 'PVD-1001'
  and not exists (
    select 1
    from public.flyers f
    where f."providerId" = public.colleges_agreements.id
      and f."filePath" = 'sample-flyer.pdf'
  );

insert into public.enrolments ("collegeId", "enrolmentUrl", username, password, email, "formsData")
select
  id,
  'https://enrol.example.edu.au',
  'student_portal',
  'portal123',
  'enrolment@nals.local',
  '[{"name":"Passport","file":null},{"name":"Academic Transcript","file":null}]'::jsonb
from public.colleges_agreements
where
  "providerId" = 'PVD-1001'
  and not exists (
    select 1
    from public.enrolments e
    where e.email = 'enrolment@nals.local'
      and e."collegeId" = public.colleges_agreements.id
  );
