-- Enrolments + flyers (matches backend/server.js Supabase payloads).
-- No foreign keys here so this always runs even if you create tables out of order.
-- Run in Supabase → SQL Editor, or: cd backend && npm run db:apply-tables (needs DATABASE_URL in .env)

create table if not exists public.flyers (
  id bigint generated by default as identity primary key,
  "providerId" bigint not null,
  "filePath" text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.enrolments (
  id bigint generated by default as identity primary key,
  "collegeId" bigint,
  "enrolmentUrl" text,
  username text,
  password text,
  email text,
  "formsData" jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_flyers_provider_id on public.flyers ("providerId");
create index if not exists idx_enrolments_college_id on public.enrolments ("collegeId");

alter table public.flyers disable row level security;
alter table public.enrolments disable row level security;

grant usage on schema public to anon, authenticated, service_role;
grant select, insert, update, delete on public.flyers to anon, authenticated, service_role;
grant select, insert, update, delete on public.enrolments to anon, authenticated, service_role;

-- Refresh PostgREST schema cache (fixes "not in the schema cache" right after CREATE)
notify pgrst, 'reload schema';
